version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      ONLINE_MODE: "false"
    ports:
      - "25565:25565"
    volumes:
      - ./volumen:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
